Py4GW_widget_manager.py

added a pop-out button that looks like a menu - added a toggle button next to it that has dynamic text to replace the checkbox.
Adjusted how widgets are loaded so that the collapsing menus are loaded and the toggle controls if they are active or not

added reload option, modified layout

---

Py4GW_widget_manager.py

Reverts apoguita/Py4GW#2  need testing

Revert "added reload option, modified layout"

---

Py4GWCoreLib/Agent.py

Changing GetModelId to return PlayerNumber instead, which is equal to the model for non players.

Fix GetModelId Agent.py

---

Py4GW_widget_manager.py

reload button and toggle widget button.
Give it a test - before it was confusing cause english is stupid but this should be better.

added a reload button, changed the checkbox to a button

---

Salvager.py

-fixing broken color style push for warnings and reusing function for showing bags
-Cleanup Syntax for improper function 'overloading'

Fixing Salvager.py logs

---

Bots/Nikon Scripts/BotUtilities.py
Bots/Nikon Scripts/Kabob_Farm.py
Bots/Nikon Scripts/WindowUtilites.py

Fixed bot incorrectly withdrawing 100 plat when 5k is already in inv, and also deposit all 5k if exactly 5k
-fixed salvage routine (still need some time testing ping)
-fixed stuck testing and position discrepancies, detect hp dmg when no enemies and hos to fix
-added config option for minimum number slots,
-ensured config options all update script in real time as they are selected (unless already in a function, will affect next round)
-only salvage when salvage items is selected
-added ping checking for waiting for actions to complete

Update to fix salv only mode and ping check

---

Bots/Nikon Scripts/BotUtilities.py
Bots/Nikon Scripts/Items.py
Bots/Nikon Scripts/Kabob_Farm.py
Bots/Nikon Scripts/Soup_Farm.py
Bots/Nikon Scripts/WindowUtilites.py

-Adding distance measure
-Adjusting requirements
-Checking surrounded adjustments

Adding soup farmer

---

Bots/Nikon Scripts/BotUtilities.py
Bots/Nikon Scripts/Items.py
Bots/Nikon Scripts/Kabob_Farm.py
Bots/Nikon Scripts/Soup_Farm.py

-Add utility to get dye color id from modstruct
-Add cast skill by id and slot (so its not querying constantly from game context for slot)

Adjusting soup farmer to correctly detect dye

---

Bots/Nikon Scripts/BotUtilities.py
Bots/Nikon Scripts/Enemies.py
Bots/Nikon Scripts/Items.py
Bots/Nikon Scripts/Kabob_Farm.py
Bots/Nikon Scripts/Salad_Farm.py
Bots/Nikon Scripts/Soup_Farm.py

-Add salad farmer first cut
-Fixing casting slowdown, pass slot now
-Fix dye model ids
-Add enemies mode id file

Adding salad farmer

---

Bots/Nikon Scripts/BotUtilities.py
Bots/Nikon Scripts/Items.py
Bots/Nikon Scripts/Salad_Farm.py
Bots/Nikon Scripts/WindowUtilites.py

-added dye model and dye color modstruct values

Updating Salad Farm 

---

Bots/Nikon Scripts/BotUtilities.py
Bots/Nikon Scripts/Kabob_Farm.py
Bots/Nikon Scripts/Salad_Farm.py
Bots/Nikon Scripts/Soup_Farm.py

if item has owner and owner is player id, continues pickup checks -remove extraneous CheckSurrounded function

Adding player id to pickup item

---

Bots/Nikon Scripts/Items.py

Gray Dye mod struct id is 11 not 1

fixing gray dye id

---

Bots/Nikon Scripts/Kabob_Farm.py
Bots/Nikon Scripts/Salad_Farm.py

should only check second profession after trying to load the skillbar

removing secondary profession check before loading skillbar

---

Bots/BorealBot_Async_example.py

adjusted boreal to use correct Routines as they had changed.

boreal_async_fix

---

Bots/Py4GW - LDoA.py

Py4GW - LDoA.py:
Sort item.loot ByDistance making bot loot closest item to it first

Update Py4GW - LDoA.py

---

Bots/Py4GW - LDoA.py
Py4GWCoreLib/enums.py

Py4GW - LDoA.py:
Fixed AlwaysAutoRezise in BotVars()
Re-ordered InventoryTracker Items list (Yeah i know OCD)
Fixed Size and Position in DrawWindow()

Update Py4GW - LDoA.py & enum.py

---

Bots/Py4GW - LDoA.py
Py4GWCoreLib/Agent.py
Py4GWCoreLib/Party.py
Py4GWCoreLib/Routines.py

Py4GW.py:
Adeded LDoA_TravelToOutpost()
Added LDoA_TravelToDistrict()
Added enemy_array Sort.ByDistance()
Added current_health_pct (percentage of health) to Survivor(), Death() & Survivor_Hamnet()
Changed enemy_array Filter.ByDistance() to a tad smaller number (fixing standing just out of combat doing nothing when utilizing HeroAI for combat)
Added FSM_vars.last_target_id
Changed Profession check to utilize enum.py's Profession enum
Changed handle_loot(), Added item_distance as a variable
Added handle_lootFlower() and handle_map_path_Red_Iris_Flower()
Added self.last_target_id & self.PetBehavior to StateMachineVars class
Changed Map.Travel() to use LDoA_TravelToOutpost() instead in state_machine's
Changed Map.TravelToDistrict() to use LDoA_TravelToDistrict() instead in state_machine's …

Update Py4GW.py, Agent.py, Party.py & Routines.py

---

Widgets/RerollCharacter.py

reroll widget

---

Py4GWCoreLib/Py4GWcorelib.py

added event transitions to FSM class - backwards compatible so no changes needed to existing FSM code.
added log actions flag to console printing - reduce console spam when not debugging
added on_exit/on_enter to AddWaitState - available in other states missed adding it to this.
removed redundant functions - functions that arnt USED at all, arn't useful or arnt user friendly

Fsm adjust

---

Py4GWCoreLib/Py4GWcorelib.py

causing looping with certain conditions - adjusting timer reset.

Fsm bugfix

---

Bots/Rollerbeetle Racing.py

Adds a Rollerbeetle Racing Bot, which runs the race until stopping. Some improvements listed in the top of the file to be made later by me or anyone.

Rollerbeetle Racing Bot

---

Bots/Proof Of Legend Farmer.py

fixed max, min, avg timers and changed success rate to %

fix timers, fix success rate

---

Bots/Proof Of Legend Farmer.py

adjust add hero and henchie to be numerals. adjust timings which work better.

Proof farmer

---

Bots/Proof Of Legend Farmer.py

proof of legend adjustments and a couple of bug fixes.

proof farmer timings and bug fixes

---

Bots/Rollerbeetle Racing.py

Using skill IDs, FSM fixes, skill logic changes
Current state:

Rollerbeetle bot fixes

---

Bots/Example Bots/Vaettir Async v2.4.py

Target handling when casting hos

Update Vaettir Async v2.4.py

---

Py4GW_widget_manager.py

written to be singleton
only one instance should exist even if you call it etc
added some directory checks just to make sure it knows where /widget is
added ability to see enabled widgets etc for debug logs

singleton instance of Py4GW_widget_manager.py

---

Bots/Proof Of Legend Farmer.py

Removed some debug
added an enabled check to the delete button for bringing up the delete pop up window.
adjusted timings to be a middle ground.

more changes to proof

---

Bots/Proof Of Legend Farmer.py

added cinematic check to end of create character
cleared the click cache after exiting clicking
added under lvl 5 check to after kamadan quest hand in - this should go outside and farm to lvl 5 wild card.

added under lvl 5 check

---

Bots/Proof Of Legend Farmer.py

Added an extra frame check in character select, increased wait
I managed to recreate a crash when there is some net lag, this should fix that

add extra check in create chara

---

Py4GWCoreLib/Routines.py

When evaluating energy cost after effects while under healer's covenant.

Fixed a small bug

---

Widgets/Pet Helper.py

Current version, should no longer crash on Map Transit, should no longer show Pet Helper in Outpost, Should no longer try to issue orders to none existent pet

Update Pet Helper.py

---

Bots/Proof Of Legend Farmer.py

Change create/delete timings
Changed the method used to move through some menus in the chara select - hopefully more stable (less crashes)
Removed a lot of steps to simplify debugging
Adjusted some functions to be more safe in regards to frame availability

proof farmer changes

---

HeroAI/combat.py

Revert "fix PrioritizeSkills algorithm"

---

Widgets/Mission Map +.py

Increased delay to 3000 milliseconds since I was still experiencing crashes at 1 second.

Increased MissionMap load delay

---

Widgets/LootManager.py

Revert "Update LootManager.py"

---

Blessed_helpers/Blessing_Core.py
Blessed_helpers/Blessing_dialog_helper.py
Blessed_helpers/Verify_Blessing-py
Blessed_helpers/__init__.py
Blessing_UI.py
Py4GW.ini
Widgets/Config/Blessed_Config.ini

Blessing widget

---

Py4GWCoreLib/enums.py
Widgets/Pet Helper.py

enums.py:
Added Special characters to Key Enum.
Pet Helper.py:
Clean up of empty lines and fix of reset variables to only do it if they need updating.
Added Opening of Pet Window (') US & English (ø) Danish if in explorable area with a 3000 ms delay.
Added Wipe check, will set Pet to Guard if party wipes.

Update of enums.py & Pet Helper.py

---

Widgets/Dialog Sync.py

Update Dialog Sync.py

---

Widgets/widget_manager/config_scope.py
Widgets/widget_manager/handler.py
Widgets/widget_manager/main.py
Widgets/widget_manager/settings_io.py
Widgets/widget_manager/state.py
Widgets/widget_manager/ui_config_sections.py
Widgets/widget_manager/ui_embedded_config.py
Widgets/widget_manager/ui_floating_menu.py
Widgets/widget_manager/ui_old_menu.py
Widgets/widget_manager/ui_quickdock.py
Widgets/widget_manager/ui_widget_menu.py

Revert "refactor(widget_manager): widget config scope to fix circular reference and fix floating button drag logic"

---

Widgets/Switch Character.py

Refactored is_in_character_select into a reusable function and updated all reference in switch character for consistent and accurate state checks.

fix(config): improve character select detection reliability

---

Widgets/Data/Nick_cycles.json
Widgets/LootManager.py

Nicks items and a nice handly feature to add them to loot filter

Updated loot manager

---

Widgets/Dialog Sync.py

This has a couple of improvements and has been stable for me for 8 hours no crash

updated shared dialog

---

Widgets/Survival Title Helper.py

Fixed sliders being coupled (they should not be)

Update Survival Title Helper.py

---

Widgets/widget_manager/config_scope.py
Widgets/widget_manager/main.py
Widgets/widget_manager/ui_config_sections.py
Widgets/widget_manager/ui_embedded_config.py
Widgets/widget_manager/ui_floating_menu.py
Widgets/widget_manager/ui_old_menu.py

Improved character select detection to run only once when needed, avoiding unnecessary frame ID lookups.

perf(ui): throttle character select updates

---

Widgets/Switch Character.py
Widgets/widget_manager/main.py
Widgets/widget_manager/ui_old_menu.py

Adjusted the switch character character select check to be more resilient to failure.
Reduced function calls in widget manager main, added throttle to old menu ini interaction

perf(widget_manager), fix(switch character)

---

HeroAI/windows.py

As title, 
Adds default flagging utility for any party size.

added formation flagging, double backline/single backline

---

HeroAI/windows.py

Made set formations to be a clean dictionary. 
Added narrow versions of the flag and triple row wide and narrow versions.

[Formations][Flagging] Cleaned up code for formations

---

Widgets/Compass +.py
Widgets/Config/Compass +.ini

custom markers per model id (playernumber)

custom markers

---

Widgets/Compass +.py

changed dead markers from alpha mod to transition to black
changed custom marker ui + other ui improvements
fixed compass showing in cinematics (hopefully)
changed draw order to draw gadgets first

small improvements

---

Widgets/HeroAI.py

[FLAGGING] Fix Absolute positioning

---

HeroAI/windows.py
Py4GWCoreLib/enums.py
Widgets/CombatPrep.py
Widgets/HeroAI.py
Widgets/Messaging.py
Widgets/widget_manager/default_settings.py

…NO_HOTKEYS"
This reverts commit e5bbd3c21b41f5d40a0ca52d0dd1f2af542cd577, reversing changes made to 7a89e1c7facab5ee294c232ab22ecdbf72892756.

[COMBAT_PREP] Revert of the revert, NO HOTKEYS

---

Py4GW.ini

[COMBAT_PREP] ini fix

---

HeroAI/windows.py
Widgets/Messaging.py

Corrected float to int parameter
Changed Dialog button to use correct function
tested & sucess

HeroAI Integrated TakeDialog fix

---

Py4GW.ini
Widgets/Skillbar +.py

skillbar recharge timers
effect duration timers
autocast features (keep shadowform up while afk, etc)

added skillbar+, includes:

---

Widgets/Style Manager.py

Forgot to remove some bloat and load the selected theme on load ... Oops

Update Style Manager.py

---

Bots/aC_Scripts/Titlehelper/ItemSelector.py
Bots/aC_Scripts/Titlehelper/titlehelper_main.py
Py4GW.ini
Widgets/TitleHelper.py

Drink some Alcohol
Eat some Sweets
Party hard and gain some titles

TitleHelper by aC

---

Widgets/Profession Unlocker

Update to the semi broken one from before

Profession Unlocker final

---

Widgets/LootManager.py

added select all and deselect all as well as a dye section

LootManager.py

---

.gitignore
Bots/AlcoholProc.py

Script to block keybinds, consume alcohol and activate the skill.

[ALCOHOL_PROC] Added alcohol procfor the poor people

---

Widgets/CanthaDialogSender.py
Widgets/NFDialogSender.py

Cleaned up one time use dialogs.

[DIALOG_SENDER] Updated with eternal forge master

---

Bots/aC_Scripts/OutpostRunner/Build_Manager_Addon.py
Bots/aC_Scripts/Outpostrunner v1.0.py

Update Outpostrunner v1.0.py

---

Py4GWCoreLib/Builds/ShadowFormMesmerVaettir.py

[YVAB] removed the d

---

Bots/ConsPrinter.py

Bot script to sell unwanted common items and make consets.

[CONS] Cons Printing

---

Py4GW.ini

[INI][COMBAT_PREP] Added to hero AI as its dependent on it

---

Widgets/Skillbar +.py

fixed effect durations not resetting when recast
fixed skillbar draws being placed on wrong skill

various fixes

---

Bots/Nightfall_leveler.py
Bots/Wick Divinus bots/PVE skills unlock bot by Wick Divinus and Kendor.py

minor coord changes to NF leveler. Renamed some lines in the skill bot to point to the right header #'s

changed some stuff

---

Bots/Nightfall_leveler.py

Fixed for 2 classes and tested

Fix Headpiece armor

---

Bots/marks_coding_corner/DervCOFFarm.py
Bots/marks_coding_corner/DervDustFarm.py
Bots/marks_coding_corner/VaettirMarksMods.py
Bots/marks_coding_corner/utils/loot_utils.py
Py4GWCoreLib/Builds/DervDustFarmer.py

* Added a threshold for vaettir that makes it so it casts HOS when its running in circles within a single spot while traversing the path
* Added side step to Dust bot to sidestep the giant boss before killing the stupid aloe.

[DUST][VAETTIR] Fix stuck mechanics

---

Widgets/EZ Cast.py

Added dev options and separated Refrain Maintainer into its own tab

Update EZ Cast.py
